services:
  - type: web
    env: python
    name: HeartInGestures
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run pages/Main.py --server.port $PORT --server.enableCORS false
    pythonVersion: 3.14.3
